"""Phase 0/1 audit reports over the repository's historical dataset."""

from __future__ import annotations

from collections import Counter
from datetime import date, timedelta
from pathlib import Path

from nsefc.calendar import TradingCalendar, reconcile
from nsefc.ingestion.providers.historical_file import (
    DailyMove,
    daily_moves,
    price_files,
    profile_file,
)

SATURDAY = 5
GAP_MIN_WEEKDAYS = 10  # a run of at least this many weekdays without data is a data gap
LARGEST_MOVES_SHOWN = 40


def _weekday_gaps(dates: set[date], start: date, end: date) -> list[tuple[date, date, int]]:
    """Runs of >= GAP_MIN_WEEKDAYS consecutive weekdays with no data."""
    gaps: list[tuple[date, date, int]] = []
    run: list[date] = []
    day = start
    while day <= end:
        if day.weekday() < SATURDAY:
            if day in dates:
                if len(run) >= GAP_MIN_WEEKDAYS:
                    gaps.append((run[0], run[-1], len(run)))
                run = []
            else:
                run.append(day)
        day += timedelta(days=1)
    if len(run) >= GAP_MIN_WEEKDAYS:
        gaps.append((run[0], run[-1], len(run)))
    return gaps


def coverage_markdown(data_dir: Path) -> str:
    profiles = [profile_file(p) for p in price_files(data_dir)]
    all_dates: set[date] = set()
    lines = [
        "# Historical data coverage",
        "",
        f"Generated by `nsefc data profile` from `{data_dir}`. Equity rows only; index rows "
        "(codes starting with ^) are counted separately.",
        "",
        "| File | Rows | First | Last | Sessions | Equities | Index codes | Unparsed dates "
        "| Duplicate keys |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    headers: Counter[tuple[str, ...]] = Counter()
    for p in profiles:
        all_dates.update(p.dates)
        headers[tuple(p.header)] += 1
        lines.append(
            f"| {p.path.name} | {p.rows:,} | {p.first} | {p.last} | {len(p.dates)} | "
            f"{len(p.equity_codes)} | {len(p.index_codes)} | {p.unparsed_dates} "
            f"| {p.duplicate_keys} |"
        )
    if not all_dates:
        return "\n".join([*lines, "", "No dated rows found."]) + "\n"
    start, end = min(all_dates), max(all_dates)
    lines += ["", "## Header variants", ""]
    for header, count in headers.most_common():
        lines.append(f"- {count} file(s): `{', '.join(header)}`")
    lines += [
        "",
        "## Sessions per month",
        "",
        "| Year | "
        + " | ".join(
            ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        )
        + " | Total |",
        "| --- " * 14 + "|",
    ]
    by_month = Counter((d.year, d.month) for d in all_dates)
    for year in range(start.year, end.year + 1):
        counts = [by_month.get((year, m), 0) for m in range(1, 13)]
        lines.append(f"| {year} | " + " | ".join(str(c) for c in counts) + f" | {sum(counts)} |")
    lines += ["", "## Gaps of two weeks or more", ""]
    gaps = _weekday_gaps(all_dates, start, end)
    lines += [f"- {a} to {b}: {n} weekdays with no data" for a, b, n in gaps] or ["- none"]
    weekend = sorted(d for d in all_dates if d.weekday() >= SATURDAY)
    lines += ["", "## Anomalies", ""]
    lines += [f"- weekend date with data: {d} ({d:%A})" for d in weekend] or ["- no weekend dates"]
    lines += _moves_section(data_dir)
    return "\n".join(lines) + "\n"


def _moves_section(data_dir: Path) -> list[str]:
    """Daily moves against the main-board band of +/-10% (assumption A5)."""
    by_year: dict[int, Counter[str]] = {}
    beyond: list[DailyMove] = []
    for move in daily_moves(price_files(data_dir)):
        counts = by_year.setdefault(move.session_date.year, Counter())
        counts["rows"] += 1
        counts["price_set"] += move.price_set
        if move.beyond_band():
            counts["beyond"] += 1
            counts["beyond_price_set"] += move.price_set
            beyond.append(move)
    lines = [
        "",
        "## Daily moves against the 10% band (assumption A5)",
        "",
        "Day Price against the Previous price printed on the same row, for equity rows with both "
        "prices. A move counts as beyond the band when it exceeds 10% of the previous price by "
        "more than one tick (KES 0.01). Price-setting rows traded at least 100 shares "
        "(Rule 7.6.6). Recovery Board securities have a 5% band and are not separated here.",
        "",
        "| Year | Rows | Price-setting | Beyond 10% | Beyond 10%, price-setting |",
        "| --- | --- | --- | --- | --- |",
    ]
    for year, c in sorted(by_year.items()):
        lines.append(
            f"| {year} | {c['rows']:,} | {c['price_set']:,} | {c['beyond']} "
            f"| {c['beyond_price_set']} |"
        )
    total = sum((c for c in by_year.values()), Counter())
    if total["price_set"]:
        within = 1 - total["beyond_price_set"] / total["price_set"]
        lines += ["", f"{within:.3%} of price-setting rows lie within the band."]
    lines += [
        "",
        f"### Largest moves beyond the band ({min(len(beyond), LARGEST_MOVES_SHOWN)} "
        f"of {len(beyond)})",
        "",
        "Corporate actions (bonus issues, splits, rights), resumption after a suspension and the "
        "exceptions in Rule 5.10.5 are the expected explanations; the Phase 1 audit classifies "
        "each one.",
        "",
        "| Date | Code | Previous | Day Price | Change | Volume |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for m in sorted(beyond, key=lambda m: (-abs(m.change), m.session_date))[:LARGEST_MOVES_SHOWN]:
        lines.append(
            f"| {m.session_date} | {m.code} | {m.previous:,.2f} | {m.price:,.2f} "
            f"| {m.change:+.1%} | {m.volume:,} |"
        )
    if not beyond:
        lines.append("| none | | | | | |")
    return lines


def calendar_reconciliation_markdown(calendar: TradingCalendar, data_dir: Path) -> str:
    dates: set[date] = set()
    for path in price_files(data_dir):
        dates.update(profile_file(path).dates)
    if not dates:
        return "# Calendar reconciliation\n\nNo dated rows found.\n"
    start, end = max(min(dates), calendar.coverage_start), min(max(dates), calendar.coverage_end)
    gaps = _weekday_gaps(dates, start, end)
    no_data, closed_with_data = reconcile(
        calendar, dates, start, end, ignore=tuple((a, b) for a, b, _ in gaps)
    )
    by_year: dict[int, list[date]] = {}
    for day in no_data:
        by_year.setdefault(day.year, []).append(day)
    lines = [
        "# Calendar reconciliation",
        "",
        f"Generated by `nsefc calendar reconcile` from `{data_dir}`, {start} to {end}. "
        "ENGINEERING.md 7.5: for history, a date is a held session when the data shows "
        "trading; every disagreement below needs a decision in the Phase 1 audit.",
        "",
        "## Data gaps excluded from the comparison",
        "",
    ]
    lines += [f"- {a} to {b} ({n} weekdays)" for a, b, n in gaps] or ["- none"]
    lines += [
        "",
        f"## Scheduled sessions with no data ({len(no_data)})",
        "",
        "Either an unrecorded closure (add it to `config/calendar/nse_holidays.yaml` with its "
        "source) or a hole in the dataset (backfill or mark missing).",
        "",
        "| Year | Dates |",
        "| --- | --- |",
    ]
    for year, days in sorted(by_year.items()):
        lines.append(f"| {year} | " + ", ".join(f"{d:%a %d %b}" for d in days) + " |")
    lines += [
        "",
        f"## Data on days the calendar closes ({len(closed_with_data)})",
        "",
        "Either a wrong calendar entry or mis-dated rows in the dataset.",
        "",
    ]
    for day in closed_with_data:
        holiday = calendar.holiday_on(day) if day.weekday() < SATURDAY else None
        reason = holiday.name if holiday else day.strftime("%A")
        lines.append(f"- {day}: {reason}")
    if not closed_with_data:
        lines.append("- none")
    return "\n".join(lines) + "\n"
